### ISSUE TITLE
EE APP does not disable user geometry option

### ISSUE THREAD

**Issue by rfernand387** [rfernand387/LEAF-Toolbox#2]
The filter by geomtery option should be disabled when launching as an app since it is not possible to upload a geometry in an app.

**Comment by rfernand387** [comment]
I may be wrong about this.  Can GEE folks enlighten us as to how we can allow for users to upload geometries before running an app on mobile please?

**Comment by eoags** [comment]
Dear Richard, I have been using time-series Landsat and Sentinel-2 data for vegetation trend analysis (LandTrendr) and land-use/land-cover classification to assist oil and gas reclamation assessment in Alberta. Biophysical products (e.g., LAI, FAPAR, FCOVER) from the LEAF toolbox would be really useful for reclamation assessment. I am requesting a function in Earth Engine JavaScript API to utilize these biophysical products for various temporal range in Alberta.
Regards,
Subir

**Comment by Prindle19** [comment]
The best approach here is to provide the user with a drop down list of their own existing assets (this means the user would ingest them prior to using your app via the code editor or otherwise.)

Then, you'll have to populate at least one dropdown (or use a textbox to let them free-hand the asset path in) with the user's assets. 

You can get their asset roots using: 
https://developers.google.com/earth-engine/apidocs/ee-data-getassetroots
Then get a list of their assets once they choose one: (probably want to use a function to filter to FeatureCollections)
https://developers.google.com/earth-engine/apidocs/ee-data-listassets
Then push that filtered list to a ui.Select element: https://developers.google.com/earth-engine/apidocs/ui-select

**Comment by rfernand387** [comment]
NRCan will test solution in future deployment.  Closed
