### ISSUE TITLE
SL2P Dictionary issue

### ISSUE THREAD

**Issue by JakeEckersley** [rfernand387/LEAF-Toolbox#6]
Hi Richard,

Firstly, thanks for creating this toolbox - incredibly useful!

I'm encountering a new error running some code in the ee browser derived from your JS example script.

When applying the LAI processor as per below:
//  Apply LAI processor
var varName = 'LAI'
var output_collection = ee.ImageCollection(SL2P.applySL2P(input_collection,varName,dictionariesSL2P));
print(output_collection,'S2 LAI collection')

The image collection object has the following error: Dictionary.get: Dictionary does not contain key: outputScale.

I've since run the example script unedited (both the sl2p and sl2p-ccrs code) and am encountering the same error.

Any ideas?

Jake

**Comment by glemoine62** [comment]
outputScale (and outputOffset) are supposed to be in the netOptions dictionary (probably not a good choice, as it relates only to scaling the output after running the net, so would be better in colOptions). The bind apparently works (for colOptions), but since netOptions are set up internally in users/richardfernandes/SL2P:SL2P you need to hack your own copy of that.
