### ISSUE TITLE
How to make it work outside North America?

### ISSUE THREAD

**Issue by glemoine62** [rfernand387/LEAF-Toolbox#8]
Richard,

I got the basic GEE script working for S2LP after a little hack to solve missing offset parameters (in netOptions). I wanted to further test in other-than North America areas but the script does not seem to work there (throwing an ImageCollection geometryImageCollection (Error) Collection.geometry: Unable to perform this geometry operation. Please specify a non-zero error margin). This is likely due to some internal geometry check that limits to North America, linked to the need for a land cover set.

You mention in the wiki that as an alternative global Copernicus land cover can be used, but I find no code that allows one to make the switch. I guess this switch requires a complete new set of trained model outputs, probably as part of revised colOptions. Would it be possible to explain the steps to make this switch?

Guido

**Comment by rfernand387** [comment]
Hi.

Fixed the issue with mssing collection option, was due to mistaking in updating the source code.  Now using the GEE Github repo directly.  As for outside NA, it will automatically use Copernicus GLobal Land Cover.  Only caveat is this may be out of date as there is only a circa 2015 map.  That said SL2P only uses this land cover to mask out non vegetated areas.  

I will put an option in the Javascript code to use SL2P irrespective of land cover - in which case you will need to mask out areas later.   Else, you can modify the code in constructFeatureCollectionsSL2P (line 49) so that input land cover maps are owerwritten by a value of 1 everywhere (forces SL2P to apply everywhere).

Richard

**Comment by glemoine62** [comment]
Richard,


The issue with landcover is resolved, but, for some reason, it is not possible to run the code for selections in 2022. Looks like there is some fixed date range check inside the code. However, all javascript code has disappeared from the github site, so it's hard to discover where this fix may be.


Guido

________________________________
