### ISSUE TITLE
negative LAI values over low LAI environments

### ISSUE THREAD

**Issue by JakeEckersley** [rfernand387/LEAF-Toolbox#9]
Hey Richard,

Thanks for the recent updates - all running smoothly!

A couple of questions:

I'm wondering why the 'estimateLAI' output is scaled *1000 for sentinel data? Shouldn't it be left as is?

Also, I'm getting quite a few negative LAI values in the data - not sure why? The area i'm running this is over semi-arid zone Australia, potentially the reflectance values are outside of the range of inputs specified in the training data, but I thought I'd get your opinion? Attached is a script with the regions for reference.

// import region
var table = ee.Geometry.Polygon([[[120.16128707117,-23.4522820631276],	[120.16128707117,-21.4125112999302],	[116.925788830006,-21.4125112999302],	[116.925788830006,-23.4522820631276],	[120.16128707117,-23.4522820631276]]]);
//import sites
var	FRE_subpoly	= ee.Geometry.Polygon([[[119.929938728971,-23.2405161923586],	[119.929938728971,-23.1999184204295],	[119.893686287466,-23.1999184204295],	[119.893686287466,-23.2405161923586],	[119.929938728971,-23.2405161923586]]]);

// import dictionaries needed to pre process both S2 and L08 data
var dictionariesSL2P = require('users/richardfernandes/SL2P:dictionaries-SL2P-CCRS'); // Specify collection and algorithms
var S2 = require('users/richardfernandes/SL2P:toolsS2')                     // Cloud masking and geometry for S2
var L08 = require('users/richardfernandes/SL2P:toolsL8');                   // Cloud masking and geometry for L08
var ib = require('users/richardfernandes/SL2P:imageBands')                     // Cloud masking and geometry
var SL2P = require('users/richardfernandes/SL2P:SL2P-CCRS')                     // Cloud masking and geometry

// chose a collection
var collectionName = "COPERNICUS/S2_SR_HARMONIZED"      ;                              // Uncomment for L08 - check for updates on harmonized data
//var collectionName = "LANDSAT/LC08/C02/T1_L2"                               // Uncomment for S2
// filter images based on you mapBouds, date range and then preprocess

var colOptions = ee.Dictionary(ee.Dictionary(dictionariesSL2P.make_collection_options()).get(collectionName));  //dictionaries describing sensors and bands for networks
var input_collection = ee.ImageCollection(collectionName)
                           .filterBounds(table) 
                           .filterDate('2021-10-01', '2021-10-31')  
.map(S2.S2MaskClear)                                // Clear sky snow free  land mask, uncomment for S2
.map(S2.addS2Geometry.bind(null,colOptions));
print(input_collection,'S2 cloudmask collection');

//  Apply LAI processor
var varName = 'LAI'
var output_collection = ee.ImageCollection(SL2P.applySL2P(input_collection,varName,dictionariesSL2P)); // will process ALL input scenes
print(output_collection,'S2 LAI collection')

//Create a median dataset, reduce from 64 to 32 bit
var median = output_collection.select('estimateLAI').median().divide(1000).float()
print(median,'medianLAI')

// Aquire projection info for export
var projection = median.projection().getInfo();
print(projection.crs,"proj")

// Reduce the region (minimum val)
var minLAI = median.reduceRegion({
  reducer: ee.Reducer.min(),
  geometry: FRE_subpoly,
  scale: 10,
  maxPixels: 1e9
});

print(minLAI,'min');

// Reduce the region (max val)
var maxLAI = median.reduceRegion({
  reducer: ee.Reducer.max(),
  geometry: FRE_subpoly,
  scale: 10,
  maxPixels: 1e9
});

print(maxLAI,'max');

// Reduce the region (max val)
var meanLAI = median.reduceRegion({
  reducer: ee.Reducer.mean(),
  geometry: FRE_subpoly,
  scale: 10,
  maxPixels: 1e9
});

print(meanLAI,'mean');

///// script to download to drive. Edit the geometry and name for each subplot. Need to click run on the tasks tab when done
var geometry = FRE_subpoly
var clipped = median.clip(geometry);// Clip to the output image to the project boundaries
//clipped = clipped.select('estimateLAI')
print(clipped,'Median LAI clipped')
Map.centerObject(geometry); // Focus map centre on hooley ck
Map.addLayer(clipped,{min: -.8, max: 4,    palette: ['yellow', 'green']}, "LAI");  // We use maximum value composite for demonstration

// Export the image, specifying the CRS and region.
Export.image.toDrive({
  image: clipped,
  folder: 'EE_Fortescue',
  description: 'October21_Fortescue_CCRS_LAI_FRE_subpoly',
  crs: projection.crs,
  fileFormat: 'GeoTIFF',
//  crsTransform: projection.transform,
 region: geometry,
  scale: 10
});

**Comment by rfernand387** [comment]
Hi Jake,

First SORRY for long delay.  My notifications were being blocked by my Govt firewall.

If this helps:

1.  we scale by 1000 to reduce output volume , you can export using UINT16.  This is an issue for the Javascript GUI version and we did not want to change the scaling for scripting users.  I will consider maybe going back to geophysical units only.  I corrected the wiki metadata by the way.

2.  negative values are out of domain.  That means they should be flagged as poor quality in the quality band.  Even if they are not it is a good indication you are in the noise level of SL2P.  You can check this actually by seeing if the 'errorLAI' value exceeds the 'estimateLAI'.

3.  You probably dont want to composite using a median - for example the MODIS algorithm composites based on maximum fAPAR.  The reason is that MOST errors in the input reflectance will result in underestimation.  

4.  frankly your site has extremely low vegetation,  In such conditions I would use fcover rather than LAI for two reasons.  First it has much lower uncertainty in terms of precision and accuracy.  Secondly, for very sparse vegetaton it  is typically highly correlated to LAI anyways - you may need some field data to get the relationship if you really prefer LAI,

Again sorry for delay.  Richard
